### ISSUE TITLE
Decreasing arrival time

### ISSUE THREAD

**Issue by dholroyd** [russelltg/srt-rs#93]
My reading of the [`SrtSocket` description](https://docs.rs/srt-tokio/0.2.0/srt_tokio/struct.SrtSocket.html) is that client code can expect that the `Instant` value does not decrease from one yielded value to the next.

I added some logging to my application code

```rust
    let mut last_arrival_time = None;
    while let Some((arrival_time, bytes)) = sock.try_next().await.expect("sock.try_next() failed") {
        if let Some(last_arrival_time) = last_arrival_time {
            if arrival_time < last_arrival_time {
                error!("Out of order packets. last={:?} this={:?}", last_arrival_time, arrival_time);
                continue;
            }
        }
        last_arrival_time = Some(arrival_time);
        ...
    }
```
 and can see that very occasionally the value does decrease, by _10ms_ in this case,

```
[2021-04-07T11:10:03.777845477Z ERROR test::srt] Out of order packets. last=Instant { tv_sec: 4108711, tv_nsec: 501700506 } this=Instant { tv_sec: 4108711, tv_nsec: 501690506 }
```
by _8ms_ in this case,
```
[2021-04-08T06:52:01.946181252Z ERROR test::srt] Out of order packets. last=Instant { tv_sec: 4179629, tv_nsec: 670029779 } this=Instant { tv_sec: 4179629, tv_nsec: 670021779 }
```

Is my reading of the API wrong, or does this represent a problem somewhere?

**Comment by robertream** [comment]
I knew this was an issue with the initial clock sync algorithm. In the PR I just submitted, I implemented a naive algorithm to ensure monotonicity, it just reuses the last instant value if the one calculated for a message is in the past. I can add slew if needed, but since the clock sync happens quite often, so the drift ought to be fairly small, I don't think the increased complexity would be worth it.
